### ISSUE TITLE
Unlock Interval Undefined

### ISSUE THREAD

**Issue by fake-steam** [probablyraging/steam-game-idler#13]
### Describe the issue

![image](https://github.com/user-attachments/assets/170a4e16-9ef9-462e-8361-3c3a1c6d2b1f)
Unsure what caused this to occur

### Which branch of SGI?

Base

### What version of SGI are you using?

Latest version

**Comment by probablyraging** [comment]
Thanks for reporting this issue mate.

This should be fixed in `v1.3.8` with af0a280e0c37f374966db68e1affd10a16a362f8

SGI should automatically update the next time you launch it. If the slider is still showing undefined values, go to the settings page and click the `reset settings` button and that should fix it.
