### ISSUE TITLE
App not launching properly 

### ISSUE THREAD

**Issue by the-infinite-moon** [probablyraging/steam-game-idler#25]
### Describe the issue

New update seems to have broken the app (for me at least). Upon launch, app gets stuck somewhere on my desktop and I have no way of accessing it. Restarting my PC and redownloading the app does not solve this issue. Trying to download an old version is completely pointless as I'm always forced to download the latest version once it's launched. 

### Which branch of SGI?

Base

### What version of SGI are you using?

Latest version

**Comment by probablyraging** [comment]
Thanks for reporting this issue mate.

Another user had the same issue, I believe the issue was introduced in `1.4.5` with the implementatio of storing/restoring the window state. I think if there is no initial window state it tries to pick a random location, and sometimes that location is not on the screen for some reason. So in the next update I will implement something that will pick a location in the centre of the screen by default if no previous window state exists, and that should hopefully solve that issue.

But in the mean time, try this following to fix it
1. Open SGI, wait until it is fully loaded and you can click on the icon in the task bar
2. Click on the icon in the task bar to make sure the window is active
3. Hold the WINKEY and press LEFT ARRROW multiple times to cycle through window positions

If that doesn't work, try a combination of the following [WINKEY shortcuts](https://support.microsoft.com/en-au/windows/keyboard-shortcuts-in-windows-dcc61a57-8ff0-cffe-9796-cb9706c75eec#windowskey)
- Windows Key  + Down arrow key  -  Minimize app windows.
- Windows Key  + Left arrow key  -  Snap app or window left.
- Windows Key  + Right arrow key  -  Snap app or window right.
- Windows Key  + Up arrow key  -  Maximize app windows.

This should hopefully work, if not I will get a fix for it implemented shortly and update this issue

**Comment by probablyraging** [comment]
This is _should be_ fixed in `v1.5.7` with https://github.com/probablyraging/steam-game-idler/commit/e47d6d17b48bfbf33e464dfa4652c41e81d32f78

If the issue persists, feel free to reply to this issue
