### ISSUE TITLE
endless loading 

### ISSUE THREAD

**Issue by 2ofdee** [probablyraging/steam-game-idler#32]
### Describe the issue

<html>
<body>

[v1.5.21] [Error] in (getGamesList): TypeError: Cannot read properties of undefined (reading 'slice
--

</body>
</html>

### Which branch of SGI?

Base

### What version of SGI are you using?

Latest version

### Additional Information

- [ ] I have included steps to reproduce the issue
- [ ] I have included screenshots/videos
- [ ] I have included a log.txt file
- [ ] I have checked for similar issues before reporting

**Comment by probablyraging** [comment]
Thanks for reporting.

The error you're seeing is usually because your games list or profile is set to private. Double check your Steam privacy settings. Changes can take up to 5 minutes.

Also worth enabling the `delete locally saved data` in `settings > general` and  logging in and out of SGI.

If that doesn't solve the issue, we can investigate further.

**Comment by probablyraging** [comment]
The next version of SGI will display a message to the user when their game's list is unable to be retrieved
![image](https://github.com/user-attachments/assets/3153ba72-f340-4e91-9444-ba152e163e5d)
