### ISSUE TITLE
My Steam game idler can't save my information

### ISSUE THREAD

**Issue by MrBigPro** [probablyraging/steam-game-idler#45]
### Describe the issue

![Screenshot 2024-12-13 191704](https://github.com/user-attachments/assets/487bc0c3-006e-48bd-8a90-2ff4573036e9)
sessionid and steamlogin are true, but It can't save.
![Screenshot 2024-12-13 192033](https://github.com/user-attachments/assets/c6dc41d6-2c69-47eb-b720-1d66a64c74fa)
What is my problem?

### Which branch of SGI?

Base

### What version of SGI are you using?

Latest version

### Additional Information

- [ ] I have included steps to reproduce the issue
- [X] I have included screenshots/videos
- [ ] I have included a log.txt file
- [X] I have checked for similar issues before reporting

**Comment by probablyraging** [comment]
Can you share your log.txt file. Go to settings > logs > view in file explore

**Comment by MrBigPro** [comment]
> Can you share your log.txt file. Go to settings > logs > view in file explore
[log.txt](https://github.com/user-attachments/files/18126359/log.txt)

**Comment by probablyraging** [comment]
Your credentials are being saved as they should. The error you are getting is
`Dec 13 19:35:31.555 + [v1.5.25] [Error] in (handleSave): error sending request for url (https://steamcommunity.com/): error trying to connect: tcp connect error: No connection could be made because the target machine actively refused it. (os error 10061)`

It appears your connection is being forcibly closed for whatever reason. Could be firewall, antivirus, bad internet connection. The most likely culprit is your firewall.

When you first launched SGI, you might have seen [a screen asking you to allow outgoing connections](https://learn.microsoft.com/en-us/windows/security/operating-system-security/network-security/windows-firewall/images/uac.png), and you have not accepted it, try the following and see if it works;

1. Open the Windows Control Panel
2. Go to System and Security > Windows Defender Firewall
3. Click on "Allow an app or feature through Windows Defender Firewall"
4. Click "Change settings" and then "Add another app..." and then "Browse"
5. Navigate to the install directory of the app you want to add, select it, and click "Open"
6. Check the boxes for "Private" and/or "Public" networks as needed
7. Click "OK" to save the changes

By default, SGI is installed to `C:/Program Files/Steam Game Idler/` - you want to add the `Steam Game Idler.exe` to your firewall's allow list.

**Comment by probablyraging** [comment]
If that doesn't fix the issue, you will need to Google the error code `os error 10061` and see if you can find a fix.

This error is not directly related to SGI but rather your network, so I can't really help much past that, unfortunately.

**Comment by MrBigPro** [comment]
Thankyou, maybe the problem is with my network, because mt Firewall is alway turn off. I will try other fix on Google

**Comment by probablyraging** [comment]
> Thankyou, maybe the problem is with my network, because mt Firewall is alway turn off. I will try other fix on Google

If you have completely disabled Windows Defender Firewall, that wouldn't be the issue.

- Disable any proxy or VPN services you might be using
- I assume you can access https://steamcommunity.com/ from your browser without any issues?
- Temporarily disable any anti-virus you have running
- Try running SGI as administrator
- Try a different network altogether
- Try reinstalling SGI, or installing SGI on a different machine

Besides that, I really don't know what else to try, so I'm sorry if that doesn't work.

**Comment by probablyraging** [comment]
Love to hear it!

Let me know if you have any other questions.
