### ISSUE TITLE
Add Time Idled

### ISSUE THREAD

**Issue by Slaurits** [probablyraging/steam-game-idler#5]
### Describe the feature

Add a small text to show how long you've idled.
![image](https://github.com/probablyraging/steam-game-idler/assets/83727223/e4b62953-22fa-4a48-bc2e-fea5105dedbb)
![image](https://github.com/probablyraging/steam-game-idler/assets/83727223/faf75b09-4866-43c9-90b2-a4709b7c4b51)
I have given 2 examples here

### Which branch of SGI?

CLI + WebUI

### Is your feature request related to an issue?

No

**Comment by probablyraging** [comment]
I was thinking of adding something like this but decided against it because it's a bit too complicated for what it's worth.

The main issue is that we'd need to track each game's idle time separately, rather than all games together. This is because games can start or stop idling individually without affecting currently idling games.

For example, if a user is idling a group of games and then adds more games, the original games keep idling while the new games are added. Similarly, if a user stops idling some games, those games are removed while the others continue to idle.

So instead, I decided to display a timestamp in the terminal window when each game starts idling, like `12:58PM 05/06/2024 - Started idling GAME_NAME`. This way, users can see how long each game has been idling if they want to.

Thanks for the suggestion, and I hope this explanation makes sense.

**Comment by Slaurits** [comment]
Yes, thanks
