### ISSUE TITLE
Web server adress already in use??

### ISSUE THREAD

**Issue by Slaurits** [probablyraging/steam-game-idler#6]
### Describe the issue

I attempted to update and then start it again, but it gave this error, and afterwards i attempted to reinstall it again, and it still gave the same error:
![image](https://github.com/probablyraging/steam-game-idler/assets/83727223/625a3a8d-4292-4416-a009-27a43d806530)

### Which branch of SGI?

CLI + WebUI

### What version of SGI are you using?

Latest version

**Comment by probablyraging** [comment]
> Sorry about coming with all these bug and feature reports mate

Not a problem at all, I appreciate it.

This issue however is not directly related to SGI though.

This might happen because you're trying to use a `port` that is already in use by another process running on your system. Try changing the `port` in `config.json` to something not commonly used.

This might also happen because your run the web server onces, abruptly closed the terminal without gracefully exiting. When a process is abruptly terminated, your OS might not release the port it was using straight away so you'll need to use a different port temporarily or wait for it to become available again.

**Comment by Slaurits** [comment]
Hmm, ok thanks, I'll try to change port to 3000
